[2025-01-27T10:38:15.797+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-27T10:38:15.828+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Email_POC.send_email scheduled__2025-01-25T11:04:00+00:00 [queued]>
[2025-01-27T10:38:15.847+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Email_POC.send_email scheduled__2025-01-25T11:04:00+00:00 [queued]>
[2025-01-27T10:38:15.848+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-27T10:38:15.996+0000] {taskinstance.py:2889} INFO - Executing <Task(EmailOperator): send_email> on 2025-01-25 11:04:00+00:00
[2025-01-27T10:38:16.002+0000] {standard_task_runner.py:72} INFO - Started process 2891 to run task
[2025-01-27T10:38:16.006+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Email_POC', 'send_email', 'scheduled__2025-01-25T11:04:00+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/send_email.py', '--cfg-path', '/tmp/tmpbxwdcahk']
[2025-01-27T10:38:16.009+0000] {standard_task_runner.py:105} INFO - Job 104: Subtask send_email
[2025-01-27T10:38:16.198+0000] {task_command.py:467} INFO - Running <TaskInstance: Email_POC.send_email scheduled__2025-01-25T11:04:00+00:00 [running]> on host 085520d1574a
[2025-01-27T10:38:16.418+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Email_POC' AIRFLOW_CTX_TASK_ID='send_email' AIRFLOW_CTX_EXECUTION_DATE='2025-01-25T11:04:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-25T11:04:00+00:00'
[2025-01-27T10:38:16.419+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-27T10:38:16.463+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py:155 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-01-27T10:38:16.464+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-01-27T10:38:18.268+0000] {email.py:283} INFO - Sent an alert email to ['adarshchintada2@gmail.com']
[2025-01-27T10:38:20.255+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-27T10:38:20.256+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Email_POC, task_id=send_email, run_id=scheduled__2025-01-25T11:04:00+00:00, execution_date=20250125T110400, start_date=20250127T103815, end_date=20250127T103820
[2025-01-27T10:38:20.369+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-27T10:38:20.405+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-27T10:38:20.408+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
