[2025-01-27T06:49:04.506+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-27T06:49:04.541+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Report_POC.send_reports scheduled__2025-01-25T09:30:00+00:00 [queued]>
[2025-01-27T06:49:04.565+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Report_POC.send_reports scheduled__2025-01-25T09:30:00+00:00 [queued]>
[2025-01-27T06:49:04.566+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-27T06:49:04.634+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): send_reports> on 2025-01-25 09:30:00+00:00
[2025-01-27T06:49:04.640+0000] {standard_task_runner.py:72} INFO - Started process 104 to run task
[2025-01-27T06:49:04.645+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Report_POC', 'send_reports', 'scheduled__2025-01-25T09:30:00+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/report_poc.py', '--cfg-path', '/tmp/tmp3pf9revt']
[2025-01-27T06:49:04.648+0000] {standard_task_runner.py:105} INFO - Job 92: Subtask send_reports
[2025-01-27T06:49:04.786+0000] {task_command.py:467} INFO - Running <TaskInstance: Report_POC.send_reports scheduled__2025-01-25T09:30:00+00:00 [running]> on host 085520d1574a
[2025-01-27T06:49:04.962+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Report_POC' AIRFLOW_CTX_TASK_ID='send_reports' AIRFLOW_CTX_EXECUTION_DATE='2025-01-25T09:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-25T09:30:00+00:00'
[2025-01-27T06:49:04.964+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-27T06:49:05.001+0000] {logging_mixin.py:190} INFO - client data is: [{'client_id': 1, 'email': 'adarshchintada2@gmail.com', 'schedule_ist': '30 10 * * *', 'services': ['email']}, {'client_id': 2, 'email': 'adarsh.chintada@nimbleaccounting.com', 'schedule_ist': '45 10 * * *', 'services': ['email']}, {'client_id': 3, 'email': 'n180479@rguktn.ac.in', 'schedule_ist': '30 10 * * *', 'services': ['email', 'sms']}]
[2025-01-27T06:49:05.015+0000] {logging_mixin.py:190} INFO - reports are: None
[2025-01-27T06:49:05.016+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/report_poc.py", line 67, in send_reports_via_email
    report = reports.get(client_name)
             ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
[2025-01-27T06:49:05.042+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Report_POC, task_id=send_reports, run_id=scheduled__2025-01-25T09:30:00+00:00, execution_date=20250125T093000, start_date=20250127T064904, end_date=20250127T064905
[2025-01-27T06:49:05.108+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-27T06:49:05.110+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 92 for task send_reports ('NoneType' object has no attribute 'get'; 104)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/report_poc.py", line 67, in send_reports_via_email
    report = reports.get(client_name)
             ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
[2025-01-27T06:49:05.139+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-27T06:49:05.180+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-27T06:49:05.184+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
